### ISSUE TITLE
rules似乎无法使用

### ISSUE THREAD

**Issue by xiankq** [Jonny-china/postcss-px-to-viewport#2]
我在`vite`中使用了此插件  并给予rules
```
 px2viewport({
      //   unitToConvert: 'px',
      viewportWidth: 1920,
      //   unitPrecision: 5,
      //   propList: ['*'],
      //   viewportUnit: 'vw',
      //   fontViewportUnit: 'vw',
      //   selectorBlackList: [],
      //   minPixelValue: 1,
      //   mediaQuery: false,
      //   replace: true,
      //   exclude: undefined,
      //   include: undefined,
      //   landscape: false,
      //   landscapeUnit: 'vw',
      //   landscapeWidth: 568,
      rules: [
        /\/node_modules\/vant\//, // 路径的正则或者字符串
        (pixels, parsedVal, prop) => {
          if (prop.includes('font')) {
            return parsedVal * 2 + 'vmin';
          }
          return parsedVal * 2 + 'vw';
        },
      ],
    }),
```

但编译报错 
```
17:45:06 [vite] Internal server error: object is not iterable (cannot read property Symbol(Symbol.iterator))
  Plugin: vite:css
  File: C:/Users/Administrator/Desktop/git/hnyj-vis-vue3/src/assets/iconfont.css
      at C:/Users/Administrator/Desktop/git/hnyj-vis-vue3/src/assets/iconfont.css:10:3
      at C:\Users\Administrator\Desktop\git\hnyj-vis-vue3\node_modules\@jonny1994\postcss-px-to-viewport\dist\utils.js:13:90
      at Array.find (<anonymous>)
      at createPxReplace (C:\Users\Administrator\Desktop\git\hnyj-vis-vue3\node_modules\@jonny1994\postcss-px-to-viewport\dist\utils.js:13:85)      
      at Declaration (C:\Users\Administrator\Desktop\git\hnyj-vis-vue3\node_modules\@jonny1994\postcss-px-to-viewport\dist\index.js:94:91)
      at LazyResult.visitTick (C:\Users\Administrator\Desktop\git\hnyj-vis-vue3\node_modules\postcss\lib\lazy-result.js:502:16)
      at LazyResult.runAsync (C:\Users\Administrator\Desktop\git\hnyj-vis-vue3\node_modules\postcss\lib\lazy-result.js:410:30)
      at async compileCSS (C:\Users\Administrator\Desktop\git\hnyj-vis-vue3\node_modules\vite\dist\node\chunks\dep-9c153816.js:18917:27)
      at async TransformContext.transform (C:\Users\Administrator\Desktop\git\hnyj-vis-vue3\node_modules\vite\dist\node\chunks\dep-9c153816.js:18488:50)
      at async Object.transform (C:\Users\Administrator\Desktop\git\hnyj-vis-vue3\node_modules\vite\dist\node\chunks\dep-9c153816.js:38334:30)      
      at async doTransform (C:\Users\Administrator\Desktop\git\hnyj-vis-vue3\node_modules\vite\dist\node\chunks\dep-9c153816.js:53030:29)
17:45:06 [vite] Internal server error: object is not iterable (cannot read property Symbol(Symbol.iterator))
  Plugin: vite:css
  File: C:/Users/Administrator/Desktop/git/hnyj-vis-vue3/src/assets/reset.css
      at C:/Users/Administrator/Desktop/git/hnyj-vis-vue3/src/assets/reset.css:136:3
      at C:\Users\Administrator\Desktop\git\hnyj-vis-vue3\node_modules\@jonny1994\postcss-px-to-viewport\dist\utils.js:13:90
      at Array.find (<anonymous>)
      at createPxReplace (C:\Users\Administrator\Desktop\git\hnyj-vis-vue3\node_modules\@jonny1994\postcss-px-to-viewport\dist\utils.js:13:85)      
      at Declaration (C:\Users\Administrator\Desktop\git\hnyj-vis-vue3\node_modules\@jonny1994\postcss-px-to-viewport\dist\index.js:94:91)
      at LazyResult.visitTick (C:\Users\Administrator\Desktop\git\hnyj-vis-vue3\node_modules\postcss\lib\lazy-result.js:502:16)
      at LazyResult.runAsync (C:\Users\Administrator\Desktop\git\hnyj-vis-vue3\node_modules\postcss\lib\lazy-result.js:410:30)
      at LazyResult.async (C:\Users\Administrator\Desktop\git\hnyj-vis-vue3\node_modules\postcss\lib\lazy-result.js:221:30)
      at LazyResult.then (C:\Users\Administrator\Desktop\git\hnyj-vis-vue3\node_modules\postcss\lib\lazy-result.js:206:17)


```

**Comment by Jonny-china** [comment]
```js
rules : [
  [
      /\/node_modules\/vant\//, // 路径的正则或者字符串
      (pixels, parsedVal, prop) => {
        if (prop.includes('font')) {
          return parsedVal * 2 + 'vmin';
        }
        return parsedVal * 2 + 'vw';
      },
  ]
]
```
是一个二维数组，应该再套一层 `[]`, 是可以支持多个不同路径的规则

**Comment by xiankq** [comment]
感谢回复，ts重构后插件很好用
